# Site
repository: darveenvijayan/modern-resume-theme
# favicon: images/favicon.ico

# Personal info
name: Darveen Vijayan
title: Data Scientist
email: darveenvijayan.27@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: darveenvijayan
github_username:  darveenvijayan
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: darveenvijayan
linkedin_username: darveenvijayan
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Darveen. I'm an automation and optimization enthusiast. Love puzzles and great at teamwork. Highly motivated and a fast learner willing to take on any challenge the industry has to offer. 

  My top skills are: 
  <mark>Problem Solving</mark> , <mark>Cloud Computing</mark> , 
  <mark>Agile DevOps</mark> , <mark>Python</mark> , <mark>R Programming</mark> , 
  <mark>Tableau</mark> , <mark>Shiny Dashboards</mark> , <mark>Talend ETL Suite</mark> , 
  <mark>Flask API</mark> , <mark>Docker Cotainerization</mark> 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
